meta_product_name: "Smart-home-ems"
meta_title: "Smart-home-ems - The Smart App for your Smart Home!"
meta_description: "Empower your home energy management skills with the world's leading appliance manager "
meta_image: "energy_image.png" # should exist in `app/assets/images/`
